### ISSUE TITLE
Mostly works with 1.21.8, buckets crash the game

### ISSUE THREAD

**Issue by Zevac-ZSF** [bakrun/stackitem64#13]
Hi there,

I tried the latest version (1.1.2) with MC 1.21.8, so far everything seems to stack the way I configured it, I have water/-milk-/lava-/snow-buckets stacked to 16, but when I try to use one of those buckets, the game crashes (only client side, my server kept running).

I see these lines in the logs, so I tested with only Fabric API and StackItem64 as loaded mods, and it still happens:

[22:10:25] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1657.method_7337()'
	at knot/net.minecraft.class_1755.handler$zpj000$stackitem64$stackableBucket(class_1755.java:1519) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1755.method_7732(class_1755.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1755.method_7836(class_1755.java:86) ~[client-intermediary.jar:?]

Could you please have a look, and hopefully fix this?

Thank you in advance

Zevac
